[username]
show_always = true
style_user = "fg:112"

[hostname]
ssh_only = false
style = "fg:36"

[directory]
truncate_to_repo = false
truncation_length = 0
style = "bold blue"

[docker]
symbol = " "

[ruby]
style = "bold fg:88"
symbol = "  "

[rust]
style = "bold fg:203"
symbol = " "

[git_branch]
style = "bold fg:216"

[git_status]
style = "bold fg:69"
